{{ if .Values.features.invitations.enabled }}
{{- include "ocis.basicServiceTemplates" (dict "scope" . "appName" "appNameInvitations" "appNameSuffix" "") -}}
{{- $_ := set . "autoscaling" (default (default (dict) .Values.autoscaling) .Values.services.invitations.autoscaling) -}}
{{ include "ocis.hpa" . }}
{{ end }}
