{{- if .Values.services.storageusers.persistence.enabled }}
{{- include "ocis.basicServiceTemplates" (dict "scope" . "appName" "appNameStorageUsers" "appNameSuffix" "") -}}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: storage-users-clean-expired-uploads
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.services.storageusers.maintenance.cleanUpExpiredUploads.schedule | quote }}
  {{- with .Values.services.storageusers.maintenance.cleanUpExpiredUploads.timezone }}
  timeZone: {{ . | quote }}
  {{- end }}
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: {{ .Values.services.storageusers.maintenance.cleanUpExpiredUploads.startingDeadlineSeconds }}
  suspend: {{ not .Values.services.storageusers.maintenance.cleanUpExpiredUploads.enabled }}
  jobTemplate:
    spec:
      parallelism: 1
      ttlSecondsAfterFinished: 86400
      template:
        metadata:
          labels:
            app: storage-users-clean-expired-uploads
            {{- include "ocis.labels" . | nindent 12 }}
        spec:
          restartPolicy: Never
          {{- include "ocis.securityContextAndtopologySpreadConstraints" . | nindent 10 }}
          {{- include "ocis.priorityClassName" $.jobPriorityClassName | nindent 10 }}
          {{- include "ocis.hostAliases" $ | nindent 10 }}
          nodeSelector: {{ toYaml $.jobNodeSelector | nindent 12 }}
          containers:
            - name: storage-users-clean-expired-uploads
              {{- include "ocis.jobContainerImageOcis" . | nindent 14 }}
              command: ["ocis"]
              args: ["storage-users", "uploads", "sessions", "--clean"]
              securityContext:
                runAsNonRoot: true
                runAsUser: {{ .Values.securityContext.runAsUser }}
                runAsGroup: {{ .Values.securityContext.runAsGroup }}
                readOnlyRootFilesystem: true
              env:
                {{- include "ocis.serviceRegistry" . | nindent 16 }}
                # logging
                - name: STORAGE_USERS_LOG_COLOR
                  value: {{ .Values.logging.color | quote }}
                - name: STORAGE_USERS_LOG_LEVEL
                  value: {{ .Values.logging.level | quote }}
                - name: STORAGE_USERS_LOG_PRETTY
                  value: {{ .Values.logging.pretty | quote }}

                # oCIS storage driver (decomposed filesystem)
                {{- if  eq .Values.services.storageusers.storageBackend.driver "ocis" }}
                - name: STORAGE_USERS_DRIVER
                  value: ocis
                {{- end }}

                # S3ng storage driver (decomposed filesystem)
                {{- if  eq .Values.services.storageusers.storageBackend.driver "s3ng" }}
                - name: STORAGE_USERS_DRIVER
                  value: s3ng
                - name: STORAGE_USERS_S3NG_ENDPOINT
                  value: {{ .Values.services.storageusers.storageBackend.driverConfig.s3ng.endpoint | quote }}
                - name: STORAGE_USERS_S3NG_REGION
                  value: {{ .Values.services.storageusers.storageBackend.driverConfig.s3ng.region | quote }}
                - name: STORAGE_USERS_S3NG_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "secrets.s3CredentialsSecret" . }}
                      key: accessKey
                - name: STORAGE_USERS_S3NG_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "secrets.s3CredentialsSecret" . }}
                      key: secretKey
                - name: STORAGE_USERS_S3NG_BUCKET
                  value: {{ .Values.services.storageusers.storageBackend.driverConfig.s3ng.bucket | quote }}
                {{- end }}

                - name: STORAGE_USERS_JWT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "secrets.jwtSecret" . }}
                      key: jwt-secret

                - name: OCIS_TRANSFER_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "secrets.transferSecret" . }}
                      key: transfer-secret

                - name: STORAGE_USERS_MOUNT_ID
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "config.storageUsers" . }}
                      key: storage-uuid

                - name: STORAGE_USERS_SERVICE_ACCOUNT_ID
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "config.authService" . }}
                      key: service-account-id
                - name: STORAGE_USERS_SERVICE_ACCOUNT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "secrets.serviceAccountSecret" . }}
                      key: service-account-secret

                {{- include "ocis.caEnv" $ | nindent 16}}

              resources: {{ toYaml .jobResources | nindent 16 }}

              volumeMounts:
                - name: tmp-volume
                  mountPath: /tmp
                - name: {{ include "ocis.persistence.dataVolumeName" . }}
                  mountPath: /var/lib/ocis
                {{- include "ocis.caPath" $ | nindent 16}}

          {{- include "ocis.imagePullSecrets" $ | nindent 10 }}
          volumes:
            - name: tmp-volume
              emptyDir: {}
            {{- include "ocis.persistence.dataVolume" . | nindent 12 }}
            {{- include "ocis.caVolume" $ | nindent 12}}
{{ end }}
{{- if .Values.services.storageusers.persistence.enabled }}
{{- include "ocis.basicServiceTemplates" (dict "scope" . "appName" "appNameStorageUsers" "appNameSuffix" "") -}}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: storage-users-purge-expired-trash-bin-items
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.services.storageusers.maintenance.purgeExpiredTrashBinItems.schedule | quote }}
  {{- with .Values.services.storageusers.maintenance.purgeExpiredTrashBinItems.timezone }}
  timeZone: {{ . | quote }}
  {{- end }}
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: {{ .Values.services.storageusers.maintenance.purgeExpiredTrashBinItems.startingDeadlineSeconds }}
  suspend: {{ not .Values.services.storageusers.maintenance.purgeExpiredTrashBinItems.enabled }}
  jobTemplate:
    spec:
      parallelism: 1
      ttlSecondsAfterFinished: 86400
      template:
        metadata:
          labels:
            app: storage-users-purge-expired-trash-bin-items
            {{- include "ocis.labels" . | nindent 12 }}

        spec:
          restartPolicy: Never
          {{- include "ocis.securityContextAndtopologySpreadConstraints" . | nindent 10 }}
          {{- include "ocis.priorityClassName" $.jobPriorityClassName | nindent 10 }}
          {{- include "ocis.hostAliases" $ | nindent 10 }}
          nodeSelector: {{ toYaml $.jobNodeSelector | nindent 12 }}
          containers:
            - name: storage-users-purge-expired-trash-bin-items
              {{- include "ocis.jobContainerImageOcis" . | nindent 14 }}
              command: ["ocis"]
              args: ["storage-users", "trash-bin", "purge-expired"]
              securityContext:
                runAsNonRoot: true
                runAsUser: {{ .Values.securityContext.runAsUser }}
                runAsGroup: {{ .Values.securityContext.runAsGroup }}
                readOnlyRootFilesystem: true
              env:
                {{- include "ocis.serviceRegistry" . | nindent 16 }}
                {{- include "ocis.events" . | nindent 16 }}

                # logging
                - name: STORAGE_USERS_LOG_COLOR
                  value: {{ .Values.logging.color | quote }}
                - name: STORAGE_USERS_LOG_LEVEL
                  value: {{ .Values.logging.level | quote }}
                - name: STORAGE_USERS_LOG_PRETTY
                  value: {{ .Values.logging.pretty | quote }}

                - name: STORAGE_USERS_JWT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "secrets.jwtSecret" . }}
                      key: jwt-secret

                - name: OCIS_TRANSFER_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "secrets.transferSecret" . }}
                      key: transfer-secret

                - name: STORAGE_USERS_MOUNT_ID
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "config.storageUsers" . }}
                      key: storage-uuid

                - name: STORAGE_USERS_SERVICE_ACCOUNT_ID
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "config.authService" . }}
                      key: service-account-id
                - name: STORAGE_USERS_SERVICE_ACCOUNT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "secrets.serviceAccountSecret" . }}
                      key: service-account-secret

                {{- include "ocis.caEnv" $ | nindent 16}}

              resources: {{ toYaml .jobResources | nindent 16 }}

              volumeMounts:
                - name: tmp-volume
                  mountPath: /tmp
                - name: {{ include "ocis.persistence.dataVolumeName" . }}
                  mountPath: /var/lib/ocis
                {{- include "ocis.caPath" $ | nindent 16}}

          {{- include "ocis.imagePullSecrets" $ | nindent 10 }}
          volumes:
            - name: tmp-volume
              emptyDir: {}
            {{- include "ocis.persistence.dataVolume" . | nindent 12 }}
            {{- include "ocis.caVolume" $ | nindent 12}}
{{ end }}

{{- if .Values.services.storageusers.persistence.enabled }}
{{- include "ocis.basicServiceTemplates" (dict "scope" . "appName" "appNameStorageUsers" "appNameSuffix" "") -}}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: storage-users-restart-postprocessing
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.services.storageusers.maintenance.restartPostprocessing.schedule | quote }}
  {{- with .Values.services.storageusers.maintenance.restartPostprocessing.timezone }}
  timeZone: {{ . | quote }}
  {{- end }}
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: {{ .Values.services.storageusers.maintenance.restartPostprocessing.startingDeadlineSeconds }}
  suspend: {{ not .Values.services.storageusers.maintenance.restartPostprocessing.enabled }}
  jobTemplate:
    spec:
      parallelism: 1
      ttlSecondsAfterFinished: 86400
      template:
        metadata:
          labels:
            app: storage-users-restart-postprocessing
            {{- include "ocis.labels" . | nindent 12 }}

        spec:
          restartPolicy: Never
          {{- include "ocis.securityContextAndtopologySpreadConstraints" . | nindent 10 }}
          {{- include "ocis.priorityClassName" $.jobPriorityClassName | nindent 10 }}
          {{- include "ocis.hostAliases" $ | nindent 10 }}
          nodeSelector: {{ toYaml $.jobNodeSelector | nindent 12 }}
          containers:
            - name: storage-users-restart-postprocessing
              {{- include "ocis.jobContainerImageOcis" . | nindent 14 }}
              command: ["ocis"]
              args: ["storage-users", "uploads", "sessions", "--restart", "--processing=true"]
              securityContext:
                runAsNonRoot: true
                runAsUser: {{ .Values.securityContext.runAsUser }}
                runAsGroup: {{ .Values.securityContext.runAsGroup }}
                readOnlyRootFilesystem: true
              env:
                {{- include "ocis.serviceRegistry" . | nindent 16 }}
                {{- include "ocis.events" . | nindent 16 }}

                # logging
                - name: STORAGE_USERS_LOG_COLOR
                  value: {{ .Values.logging.color | quote }}
                - name: STORAGE_USERS_LOG_LEVEL
                  value: {{ .Values.logging.level | quote }}
                - name: STORAGE_USERS_LOG_PRETTY
                  value: {{ .Values.logging.pretty | quote }}

                - name: STORAGE_USERS_JWT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "secrets.jwtSecret" . }}
                      key: jwt-secret

                - name: OCIS_TRANSFER_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "secrets.transferSecret" . }}
                      key: transfer-secret

                - name: STORAGE_USERS_MOUNT_ID
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "config.storageUsers" . }}
                      key: storage-uuid

                - name: STORAGE_USERS_SERVICE_ACCOUNT_ID
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "config.authService" . }}
                      key: service-account-id
                - name: STORAGE_USERS_SERVICE_ACCOUNT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "secrets.serviceAccountSecret" . }}
                      key: service-account-secret

                {{- include "ocis.caEnv" $ | nindent 16}}

              resources: {{ toYaml .jobResources | nindent 16 }}

              volumeMounts:
                - name: tmp-volume
                  mountPath: /tmp
                - name: {{ include "ocis.persistence.dataVolumeName" . }}
                  mountPath: /var/lib/ocis
                {{- include "ocis.caPath" $ | nindent 16}}

          {{- include "ocis.imagePullSecrets" $ | nindent 10 }}
          volumes:
            - name: tmp-volume
              emptyDir: {}
            {{- include "ocis.caVolume" $ | nindent 12}}
            {{- include "ocis.persistence.dataVolume" . | nindent 12 }}
{{ end }}
