module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.23.1

replace gopkg.in/yaml.v3 => github.com/colega/go-yaml-yaml v0.0.0-20220720070545-aaba007ebc22

require github.com/helmfile/helmfile v0.169.1
