repositories:
  - name: inbucket
    url: https://inbucket.github.io/inbucket-community

releases:
  - name: inbucket
    chart: inbucket/inbucket
    namespace: inbucket
    version: 2.5.0
    labels:
      ci-lint-skip: true # skip linting this chart in CI
    values:
      - ingress:
          enabled: true
          hosts:
            - host: inbucket.kube.owncloud.test
              paths:
                - path: /
          tls:
            - secretName: inbucket-tls
              hosts:
                - inbucket.kube.owncloud.test

  - name: ocis
    chart: ../../charts/ocis
    namespace: ocis
    values:
      - externalDomain: ocis.kube.owncloud.test
      - ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: 1024m

      - insecure:
          oidcIdpInsecure: true
          ocisHttpApiInsecure: true

      - features:
          demoUsers: true # so that they can share each other files and trigger email notifications
          emailNotifications:
            enabled: true
            smtp:
              host: inbucket.inbucket.svc.cluster.local
              port: 2500
              sender: "ownCloud <noreply@ocis.kube.owncloud.test>"
              authentication: none
              encryption: none
            branding:
              enabled: false # you can set this to true if you first run `kubectl -n ocis apply -f mail-templates.yaml`
            summary:
              daily:
                enabled: true
              weekly:
                enabled: true

      - services:
          idm:
            persistence:
              enabled: true

          nats:
            persistence:
              enabled: true

          search:
            persistence:
              enabled: true

          storagesystem:
            persistence:
              enabled: true

          storageusers:
            persistence:
              enabled: true

          thumbnails:
            persistence:
              enabled: true

          web:
            persistence:
              enabled: true
