{{- if .Values.features.emailNotifications.enabled }}
{{- include "ocis.basicServiceTemplates" (dict "scope" . "appName" "appNameNotifications" "appNameSuffix" "") -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .appName }}
  namespace: {{ template "ocis.namespace" . }}
  labels:
    app: {{ .appName }}
    ocis-metrics: enabled
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .appName }}
  ports:
    - name: metrics-debug
      port: 9174
      protocol: TCP
      appProtocol: {{ .Values.service.appProtocol.http | quote}}
{{- end }}
