{{- if .Values.services.thumbnails.persistence.enabled }}
{{- include "ocis.basicServiceTemplates" (dict "scope" . "appName" "appNameThumbnails" "appNameSuffix" "") -}}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: thumbnails-cleanup
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
  annotations:
    ignore-check.kube-linter.io/latest-tag: "using the stable tag on this busybox image is better than having an outdated image"
spec:
  schedule: {{ .Values.services.thumbnails.maintenance.cleanUpOldThumbnails.schedule | quote }}
  {{- with .Values.services.thumbnails.maintenance.cleanUpOldThumbnails.timezone }}
  timeZone: {{ . | quote }}
  {{- end }}
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: {{ .Values.services.thumbnails.maintenance.cleanUpOldThumbnails.startingDeadlineSeconds }}
  suspend: {{ not .Values.services.thumbnails.maintenance.cleanUpOldThumbnails.enabled }}
  jobTemplate:
    spec:
      parallelism: 1
      ttlSecondsAfterFinished: 86400
      template:
        metadata:
          labels:
            app: thumbnails-cleanup
            {{- include "ocis.labels" . | nindent 12 }}
        spec:
          restartPolicy: Never
          {{- include "ocis.securityContextAndtopologySpreadConstraints" . | nindent 10 }}
          {{- include "ocis.priorityClassName" $.jobPriorityClassName | nindent 10 }}
          {{- include "ocis.hostAliases" $ | nindent 10 }}
          nodeSelector: {{ toYaml $.jobNodeSelector | nindent 12 }}
          containers:
            - name: thumbnails-cleanup
              {{- include "ocis.jobContainerImage" . | nindent 14 }}
              {{- include "ocis.containerSecurityContext" . | nindent 14 }}
              command: [ "/bin/sh", "/script/thumbnails-cleanup-script.sh" ]
              {{- if .Values.customCAChain.enabled }}
              env:
                {{- include "ocis.caEnv" $ | nindent 16}}
              {{ end }}
              volumeMounts:
                - name: {{ include "ocis.persistence.dataVolumeName" . }}
                  mountPath: /var/lib/ocis
                - name: script
                  mountPath: "/script"
                {{- include "ocis.caPath" $ | nindent 16}}

              resources: {{ toYaml .jobResources | nindent 16 }}

          {{- include "ocis.imagePullSecrets" $ | nindent 10 }}
          volumes:
            {{- include "ocis.persistence.dataVolume" . | nindent 12 }}
            - name: script
              configMap:
                name: thumbnails-cleanup-script-configmap
                defaultMode: 0500
            {{- include "ocis.caVolume" $ | nindent 12}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: thumbnails-cleanup-script-configmap
data:
  thumbnails-cleanup-script.sh: |
    #!/bin/sh

    find /var/lib/ocis/thumbnails \
      -{{ .Values.services.thumbnails.maintenance.cleanUpOldThumbnails.method }} \
      {{ .Values.services.thumbnails.maintenance.cleanUpOldThumbnails.deleteBefore }} \
      -exec rm -rf {} \;
    true
{{ end }}
