repositories:
  - name: minio
    url: https://charts.min.io/
  - name: vmware-tanzu
    url: https://vmware-tanzu.github.io/helm-charts

releases:
  - name: minio
    chart: minio/minio
    version: 5.4.0
    namespace: minio
    labels:
      ci-lint-skip: true # skip linting this chart in CI
    values:
      - mode: standalone
      - rootUser: ocis
      - buckets:
          - name: ocis-bucket
            policy: none
            purge: false
      - persistence:
          size: 5Gi
      - resources:
          requests:
            cpu: 100m
            memory: 128Mi
      - rootPassword: ocis-secret-key


  - name: velero
    chart: vmware-tanzu/velero
    namespace: velero
    values:
      - image:
          repository: "docker.io/velero/velero"

      - resources: 
          limits:
            memory: 2048Mi
          requests:
            cpu: 500m
            memory: 1024Mi

      - initContainers:
          - name: velero-plugin-for-aws
            image: "docker.io/velero/velero-plugin-for-aws:v1.9.0"
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins

      - snapshotsEnabled: false

      - configuration:
          clientQPS: 100.0
          clientBurst: 100
          backupStorageLocation:
            - name:
              provider: aws
              bucket: "backup-bucket"
              credential:
                name: s3-credentials-secret-aws
                key: cloud
              config:
                region: us-east-1
                s3ForcePathStyle: true
                s3Url: http://minio.minio.svc:9000
          logLevel: "debug"

      - credentials:   
          useSecret: true
          existingSecret: s3-credentials-secret-aws

      - deployNodeAgent: true

      - nodeAgent:
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1000m    
              memory: 1024Mi
      
      - extraResources: 
          - |
            apiVersion: v1
            kind: Secret
            metadata:   
              name: s3-credentials-secret-aws
            data:
              accessKey: b2Npcw==
              secretKey: b2Npcy1zZWNyZXQta2V5


  - name: ocis
    chart: ../../charts/ocis
    namespace: ocis
    values:
      - externalDomain: ocis.kube.owncloud.test
      - ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: 1024m

      - insecure:
          oidcIdpInsecure: true
          ocisHttpApiInsecure: true

      - secretRefs:
          s3CredentialsSecretRef: s3secret

      - extraResources:
          - |
            apiVersion: v1
            kind: Secret
            metadata:
              name: s3secret
            data:
              accessKey: b2Npcw==
              secretKey: b2Npcy1zZWNyZXQta2V5

      - services:
          idm:
            persistence:
              enabled: true

          nats:
            persistence:
              enabled: true

          search:
            persistence:
              enabled: true

          storagesystem:
            persistence:
              enabled: true

          storageusers:
            persistence:
              enabled: true
            storageBackend:
              driver: s3ng
              driverConfig:
                s3ng:
                  endpoint: http://minio.minio.svc.cluster.local:9000
                  bucket: ocis-bucket

          thumbnails:
            persistence:
              enabled: true

          web:
            persistence:
              enabled: true
