releases:
  - name: ocis
    chart: ../../charts/ocis
    namespace: ocis
    values:
      - externalDomain: ocis.kube.owncloud.test
      - ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: 1024m
          tls:
            - secretName: ocis-dev-tls
              hosts:
                - ocis.kube.owncloud.test

      - insecure:
          oidcIdpInsecure: true
          ocisHttpApiInsecure: true

      - features:
          demoUsers: true

      - services:
          idm:
            persistence:
              enabled: true

          nats:
            persistence:
              enabled: true

          search:
            persistence:
              enabled: true

          storagesystem:
            persistence:
              enabled: true

          storageusers:
            persistence:
              enabled: true

          thumbnails:
            persistence:
              enabled: true

          web:
            persistence:
              enabled: true
            config:
              externalApps:
                external-sites:
                  config:
                    sites:
                      - name: ownCloud
                        url: https://www.owncloud.com
                        target: external
                        color: "#0D856F"
                        icon: cloud
                        priority: 50
            additionalInitContainers:
              - name: external-sites
                image: owncloud/web-extensions:external-sites-0.4.0
                command:
                  - cp
                  - -R
                  - /var/lib/nginx/html/external-sites/
                  - /apps
                volumeMounts:
                  - name: apps
                    mountPath: /apps
              - name: advanced-search
                image: owncloud/web-extensions:advanced-search-0.3.0
                command:
                  - cp
                  - -R
                  - /var/lib/nginx/html/advanced-search/
                  - /apps
                volumeMounts:
                  - name: apps
                    mountPath: /apps
              - name: draw-io
                image: owncloud/web-extensions:draw-io-0.4.1
                command:
                  - cp
                  - -R
                  - /var/lib/nginx/html/draw-io/
                  - /apps
                volumeMounts:
                  - name: apps
                    mountPath: /apps
              - name: json-viewer
                image: owncloud/web-extensions:json-viewer-0.4.0
                command:
                  - cp
                  - -R
                  - /var/lib/nginx/html/json-viewer/
                  - /apps
                volumeMounts:
                  - name: apps
                    mountPath: /apps
              - name: photo-addon
                image: owncloud/web-extensions:photo-addon-0.3.0
                command:
                  - cp
                  - -R
                  - /var/lib/nginx/html/photo-addon/
                  - /apps
                volumeMounts:
                  - name: apps
                    mountPath: /apps
              - name: progress-bars
                image: owncloud/web-extensions:progress-bars-0.4.0
                command:
                  - cp
                  - -R
                  - /var/lib/nginx/html/progress-bars/
                  - /apps
                volumeMounts:
                  - name: apps
                    mountPath: /apps
              - name: unzip
                image: owncloud/web-extensions:unzip-0.5.0
                command:
                  - cp
                  - -R
                  - /var/lib/nginx/html/unzip/
                  - /apps
                volumeMounts:
                  - name: apps
                    mountPath: /apps
              - name: importer
                image: owncloud/web-extensions:importer-0.4.0
                command:
                  - cp
                  - -R
                  - /var/lib/nginx/html/importer/
                  - /apps
                volumeMounts:
                  - name: apps
                    mountPath: /apps
