apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: drone
servers: 1
image: rancher/k3s:v1.32.3-k3s1
options:
  k3s:
    extraArgs:
      - arg: --tls-san=k3d
        nodeFilters:
          - server:*
      - arg: --disable=servicelb
        nodeFilters:
          - server:*
      - arg: --disable=metrics-server
        nodeFilters:
          - server:*
      - arg: --disable=traefik
        nodeFilters:
          - server:*